# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

[package]
name = "npcm400"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortexm4f = { path = "../../arch/cortex-m4f" }
enum_primitive = { path = "../../libraries/enum_primitive" }
kernel = { path = "../../kernel" }

[lints]
workspace = true

[features]
uart_interrupt_driven = []
debug-i3c = []
debug-i3c-verbose = []
default = ["uart_interrupt_driven"]
